# Generated by Django 4.0.1 on 2022-04-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
