# Generated by Django 4.0.1 on 2022-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='products',
            field=models.JSONField(),
        ),
    ]
