# Generated by Django 4.0.1 on 2022-04-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usersocial_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('tara', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('watched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usersocial',
            name='social_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
