# Generated by Django 4.0.1 on 2022-04-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_usersocial_social_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='social_id',
            field=models.CharField(default='social_id', max_length=255),
        ),
    ]
