# Generated by Django 4.0.1 on 2022-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usersocial_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersocial',
            name='social_id',
            field=models.CharField(max_length=255),
        ),
    ]
