# Generated by Django 4.0.1 on 2022-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usersocial_social_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.IntegerField(max_length=32),
        ),
    ]
