# Generated by Django 4.0.1 on 2022-04-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_client_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='tara',
            new_name='country',
        ),
    ]
