# Stage 1: Build stage
FROM node:17-alpine3.14 as builder

WORKDIR /home/src/app

COPY package*.json ./
RUN npm install --force

COPY . .

RUN npm run build 

# Stage 2: Production
FROM node:17-alpine3.14

WORKDIR /home/frontend/

COPY --from=builder /home/src/app/build/ /home/frontend/
# COPY --from=builder /home/src/app/.env.prod.web /home/frontend/

# For information only
# EXPOSE 80

# ENTRYPOINT ["nginx", "-g", "daemon off;"]
