# Stage 1: Build stage
FROM node:17-alpine3.14 as builder

WORKDIR /home/src/app

COPY package*.json .
RUN npm install --force

COPY . .

RUN npm run build 

# Stage 2: Production
FROM nginx:1.21-alpine

COPY --from=builder /home/src/app /usr/share/nginx/html

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]
