version: '3.9'

services:
  web:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    env_file:
      - ./frontend/.env.prod.web
  
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn nut_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/backend/static/
      - ./backend/media/:/home/backend/media/
    expose:
      - 8000
    env_file:
      - ./backend/.env.prod.api
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/static/
      - ./backend/media/:/home/backend/media/
    ports:
      - 8000:8000
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
