version: '3.9'

services:
  web:
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 3000:3000
  
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn nut_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/accounts:/home/backend/accounts/
      - ./backend/nut_app:/home/backend/nut_app/
      - ./backend/nut_proj:/home/backend/nut_proj/
      - ./backend/sales:/home/backend/sales/
      - static_volume:/home/backend/static/
      - media_volume:/home/backend/media/
    expose:
      - 8000
    env_file:
      - ./backend/.env.prod.api
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/static/
      - media_volume:/home/backend/media/
    ports:
      - 80:8000
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
  media_volume:
