version: '3.9'

services:
  web:
    build: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
    ports:
      - 3000:3000
  
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn nut_proj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.prod.api
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.prod.db

volumes:
  postgres_data:
