FROM python:3.10-alpine3.15

RUN mkdir -p /home/backend
ENV HOME=/home/backend

WORKDIR $HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update
RUN apk add zlib-dev jpeg-dev gcc musl-dev libffi-dev
RUN pip install --upgrade pip

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN addgroup backend && adduser -S -G backend backend
RUN chown -R backend:backend $HOME
USER backend


