# Generated by Django 4.0.1 on 2022-04-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('products', models.JSONField()),
                ('watched', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
        ),
    ]
