# Generated by Django 4.0.1 on 2022-04-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='command_id',
            field=models.IntegerField(null=True),
        ),
    ]
