# Generated by Django 4.0.1 on 2022-01-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorii',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
