# Generated by Django 4.0.1 on 2022-01-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0002_alter_categorii_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('image_desc', models.ImageField(upload_to='nut_app/uploads/images')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorii',
        ),
    ]
