# Generated by Django 4.0.1 on 2022-01-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0003_category_delete_categorii'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
