# Generated by Django 4.0.1 on 2022-01-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0004_rename_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image_desc',
            field=models.ImageField(upload_to='images'),
        ),
    ]
