# Generated by Django 4.0.1 on 2022-01-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0006_alter_categories_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image_desc',
            field=models.ImageField(upload_to='nut_app/media/categories'),
        ),
    ]
