# Generated by Django 4.0.1 on 2022-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0008_remedies_feat_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('text', models.TextField()),
                ('image_desc', models.ImageField(upload_to='nut_app/media/remedies')),
            ],
        ),
        migrations.DeleteModel(
            name='Remedies_feat',
        ),
    ]
