# Generated by Django 4.0.1 on 2022-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0010_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='link',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
