# Generated by Django 4.0.1 on 2022-02-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0015_products_product_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_cod',
            field=models.IntegerField(max_length=6, null=True, unique=True),
        ),
    ]
