# Generated by Django 4.0.1 on 2022-02-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0016_products_price_alter_products_product_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_cod',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
