# Generated by Django 4.0.1 on 2022-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0020_alter_products_image_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='form',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
