# Generated by Django 4.0.1 on 2022-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0021_products_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='form',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
