# Generated by Django 4.0.1 on 2022-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0022_alter_products_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[(True, 'In stoc'), (False, 'Stoc epuizat')], default=True, max_length=10),
        ),
    ]
