# Generated by Django 4.0.1 on 2022-02-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0023_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[('in', 'In stoc'), ('out', 'Stoc epuizat')], default='in', max_length=10),
        ),
    ]
