# Generated by Django 4.0.1 on 2022-02-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0024_alter_products_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_cod',
            new_name='product_code',
        ),
    ]
