# Generated by Django 4.0.1 on 2022-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0025_rename_product_cod_products_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.CharField(choices=[('In stoc', 'In stoc'), ('Stoc epuizat', 'Stoc epuizat')], default='in', max_length=20),
        ),
    ]
