# Generated by Django 4.0.1 on 2022-02-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0026_alter_products_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='remedies',
            options={'verbose_name': 'Remedy', 'verbose_name_plural': 'Remedies'},
        ),
        migrations.AddField(
            model_name='remedies',
            name='image_short',
            field=models.ImageField(null=True, upload_to='nut_app/media/remedies'),
        ),
    ]
