# Generated by Django 4.0.1 on 2022-02-05 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0028_remedies_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedies',
            name='image_short',
        ),
    ]
