# Generated by Django 4.0.1 on 2022-02-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0029_remove_remedies_image_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedies',
            name='description',
        ),
    ]
