# Generated by Django 4.0.1 on 2022-02-06 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0031_remedies_text_prob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedies',
            name='text_prob',
        ),
        migrations.AlterField(
            model_name='remedies',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
