# Generated by Django 4.0.1 on 2022-02-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0032_remove_remedies_text_prob_alter_remedies_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel_art',
            fields=[
                ('remedy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nut_app.remedies')),
            ],
        ),
    ]
