# Generated by Django 4.0.1 on 2022-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0033_carousel_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel_art',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
