# Generated by Django 4.0.1 on 2022-02-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0034_carousel_art_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel_art',
            name='title',
        ),
    ]
