# Generated by Django 4.0.1 on 2022-02-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0037_alter_carousel_art_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carousel_art',
            new_name='Carouselart',
        ),
    ]
