# Generated by Django 4.0.1 on 2022-02-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0038_rename_carousel_art_carouselart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carouselart',
        ),
    ]
