# Generated by Django 4.0.1 on 2022-02-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0039_delete_carouselart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carouselart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('remedy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nut_app.remedies')),
            ],
        ),
    ]
