# Generated by Django 4.0.1 on 2022-02-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0040_carouselart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carouselart',
        ),
    ]
