# Generated by Django 4.0.1 on 2022-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0042_articlefeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlecollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_desc', models.ImageField(upload_to='nut_app/media/articlecollections')),
            ],
        ),
    ]
