# Generated by Django 4.0.1 on 2022-02-10 17:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nut_app', '0046_alter_products_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='contraindications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
